### ISSUE TITLE
Prune - Remove Link Tab from Game Entry

### ISSUE THREAD

**Issue by OSXLich-Doug** [Lich5/Lich5#1]
This removes the logic to link website -> SGE -> etc, from the game entry process and removes the tab from the window presented to the user.

**Comment by mrhoribu** [comment]
Is linking to SGE not something desired to be done anymore? Or just taking out the complexity of what Lich handles. I'm not a huge fan of SGE to begin with as it's so old and outdated. There's really no need to use it that I can see, but just didn't know what the reasoning behind the removal is unless it's what I stated already. The #2 code entry looks good from what I can tell and will test it later tonight when home.

**Comment by OSXLich-Doug** [comment]
Unnecessary.  And I want to remove the win32 stuff, which this tab calls.  So it's the easiest part of the cull for me to practice on.
