### ISSUE TITLE
Bug: autostart.lic - executes repo unset-lich-updatable every run

### ISSUE THREAD

**Issue by OSXLich-Doug** [Lich5/Lich5#8]
The current iteration of autostart.lic distributed with Lich5 purposefully removes lich from the updatable pool.  This is required to prevent the Lich4 repo activities from overwriting Lich5's file.

Every login, every character, the autostart script enforces a repo unset-lich-updatable.  The logic change required is to detect the current state of repository's lich-updatable state, and take action where required.

**Comment by mrhoribu** [comment]
Fixed via #9
